node {
    stage('SCM') {
        checkout scm
    }

    stage('Install Dependencies') {
        dir('Monitoring-Project/app') {
            sh 'npm install'
        }
    }

    stage('SonarQube Analysis') {
        dir('Monitoring-Project') {
            def scannerHome = tool 'SonarScanner'

            withSonarQubeEnv('sonarqube') {
                sh "${scannerHome}/bin/sonar-scanner"
            }
        }
    }

    stage('Docker Build') {
        dir('Monitoring-Project/app') {
            sh 'docker build -t monitoring-app:latest .'
        }
    }
    stage('Trivy Security Scan') {
        sh 'trivy image --severity HIGH,CRITICAL --exit-code 1 monitoring-app:latest'
    }
}
