node {
    stage('SCM') {
        checkout scm
    }

    stage('SonarQube Analysis') {
        dir('Monitoring-Project') {
            def scannerHome = tool 'sonar-scanner'

            withSonarQubeEnv() {
                sh "${scannerHome}/bin/sonar-scanner"
            }
        }
    }
}
